name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pipx and poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install --user pipx
        pipx install poetry
    - name: Install dependencies with poetry
      run: |
        poetry env use python
        poetry install
    - name: Analysing the code with pylint and fix code
      run: |
        poetry run lint
        poetry run fix
    # - name: Install dependencies
    #   run: |
    #     python -m pip install --upgrade pip
    #     pip install pylint
    # - name: Analysing the code with pylint
    #   run: |
    #     pylint $(git ls-files '*.py')
